/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Swap: {
      address: "0xed1db453c3156ff3155a97ad217b3087d5dc5f6e",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "systemContractAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "gatewayAddress",
              type: "address",
              internalType: "address payable",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "gateway",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract GatewayZEVM",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "onCall",
          inputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct MessageContext",
              components: [
                {
                  name: "origin",
                  type: "bytes",
                  internalType: "bytes",
                },
                {
                  name: "sender",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "chainID",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "zrc20",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "message",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "onRevert",
          inputs: [
            {
              name: "revertContext",
              type: "tuple",
              internalType: "struct RevertContext",
              components: [
                {
                  name: "sender",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "asset",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "revertMessage",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "systemContract",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract SystemContract",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "Reverted",
          inputs: [
            {
              name: "recipient",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
            {
              name: "asset",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AdditionsOverflow",
          inputs: [],
        },
        {
          type: "error",
          name: "CantBeIdenticalAddresses",
          inputs: [],
        },
        {
          type: "error",
          name: "CantBeZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "IdenticalAddresses",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientInputAmount",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientLiquidity",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidPath",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidPathLength",
          inputs: [],
        },
        {
          type: "error",
          name: "MultiplicationsOverflow",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
      ],
      inheritedFunctions: {
        onCall: "contracts/UniversalContract.sol",
      },
    },
    EvmDustTokens: {
      address: "0xf7cd8fa9b94db2aa972023b379c7f72c65e4de9d",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "gatewayAddress",
              type: "address",
              internalType: "address payable",
            },
            {
              name: "_swapRouter",
              type: "address",
              internalType: "contract ISwapRouter",
            },
            {
              name: "_WETH9",
              type: "address",
              internalType: "address payable",
            },
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
            {
              name: "_permit2",
              type: "address",
              internalType: "contract IPermit2",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "ReceiveTokens",
          inputs: [
            {
              name: "outputToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "SwapAndBridgeTokens",
          inputs: [
            {
              name: "swaps",
              type: "tuple[]",
              internalType: "struct SwapInput[]",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "minAmountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "universalApp",
              type: "address",
              internalType: "address",
            },
            {
              name: "payload",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "nonce",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "signature",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "WETH9",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address payable",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "addToken",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "feeTier",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint24",
              internalType: "uint24",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "gateway",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract GatewayEVM",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getBalances",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "addresses",
              type: "address[]",
              internalType: "address[]",
            },
            {
              name: "names",
              type: "string[]",
              internalType: "string[]",
            },
            {
              name: "symbols",
              type: "string[]",
              internalType: "string[]",
            },
            {
              name: "decimalsArray",
              type: "uint8[]",
              internalType: "uint8[]",
            },
            {
              name: "balances",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasPermit2Allowance",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "requiredAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isTokenWhitelisted",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "onRevert",
          inputs: [
            {
              name: "revertContext",
              type: "tuple",
              internalType: "struct RevertContext",
              components: [
                {
                  name: "sender",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "asset",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "revertMessage",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "permit2",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IPermit2",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "removeToken",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "signatureBatchTransfer",
          inputs: [
            {
              name: "swaps",
              type: "tuple[]",
              internalType: "struct SwapInput[]",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "minAmountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "nonce",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "signature",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "swapRouter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISwapRouter",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenList",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "whitelistedTokens",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Reverted",
          inputs: [
            {
              name: "recipient",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "asset",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SwappedAndDeposited",
          inputs: [
            {
              name: "executor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "swaps",
              type: "tuple[]",
              indexed: false,
              internalType: "struct SwapOutput[]",
              components: [
                {
                  name: "tokenIn",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "tokenOut",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountIn",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "amountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "totalTokensReceived",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SwappedAndWithdrawn",
          inputs: [
            {
              name: "receiver",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "outputToken",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "totalTokensReceived",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenAdded",
          inputs: [
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenRemoved",
          inputs: [
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {
        owner: "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        renounceOwnership:
          "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
        transferOwnership:
          "lib/openzeppelin-contracts/contracts/access/Ownable.sol",
      },
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
