/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    UniversalDApp: {
      address: "0xb037e4672340298c575529277ebf5770a4147040",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_systemContract",
              type: "address",
              internalType: "address",
            },
            {
              name: "_gateway",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "gateway",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IGatewayZEVM",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "onCall",
          inputs: [
            {
              name: "context",
              type: "tuple",
              internalType: "struct MessageContext",
              components: [
                {
                  name: "origin",
                  type: "bytes",
                  internalType: "bytes",
                },
                {
                  name: "sender",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "chainID",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "zrc20",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "message",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "onRevert",
          inputs: [
            {
              name: "revertContext",
              type: "tuple",
              internalType: "struct RevertContext",
              components: [
                {
                  name: "sender",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "asset",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "revertMessage",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "systemContract",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract SystemContract",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "Reverted",
          inputs: [
            {
              name: "recipient",
              type: "bytes",
              indexed: true,
              internalType: "bytes",
            },
            {
              name: "asset",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SwappedAndWithdrawn",
          inputs: [
            {
              name: "recipient",
              type: "bytes",
              indexed: true,
              internalType: "bytes",
            },
            {
              name: "asset",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AdditionsOverflow",
          inputs: [],
        },
        {
          type: "error",
          name: "CantBeIdenticalAddresses",
          inputs: [],
        },
        {
          type: "error",
          name: "CantBeZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "IdenticalAddresses",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientInputAmount",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientLiquidity",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidChainToken",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidPath",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidPathLength",
          inputs: [],
        },
        {
          type: "error",
          name: "MultiplicationsOverflow",
          inputs: [],
        },
        {
          type: "error",
          name: "NotGateway",
          inputs: [],
        },
        {
          type: "error",
          name: "NotSupportedChainID",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
      ],
      inheritedFunctions: {
        onCall: "contracts/interfaces/IUniversalContract.sol",
      },
    },
    EvmDustTokens: {
      address: "0x6e8169401c0655ef6ab62505377a0b49039327a9",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_gateway",
              type: "address",
              internalType: "contract IGatewayEVM",
            },
            {
              name: "_swapRouter",
              type: "address",
              internalType: "contract ISwapRouter",
            },
            {
              name: "_universalDApp",
              type: "address",
              internalType: "address",
            },
            {
              name: "_wNativeToken",
              type: "address",
              internalType: "address payable",
            },
            {
              name: "_initialOwner",
              type: "address",
              internalType: "address",
            },
            {
              name: "_permit2",
              type: "address",
              internalType: "contract IPermit2",
            },
            {
              name: "_tokenList",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "ReceiveTokens",
          inputs: [
            {
              name: "outputToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "recipient",
              type: "address",
              internalType: "address",
            },
            {
              name: "minAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "SwapAndBridgeTokens",
          inputs: [
            {
              name: "swaps",
              type: "tuple[]",
              internalType: "struct EvmDustTokens.SwapInput[]",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "minAmountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "message",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "nonce",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "signature",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "SwapTokens",
          inputs: [
            {
              name: "swaps",
              type: "tuple[]",
              internalType: "struct EvmDustTokens.SwapInput[]",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "minAmountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "outputToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "nonce",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "signature",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "acceptOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "addTokens",
          inputs: [
            {
              name: "tokens",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "collectedFees",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "gateway",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IGatewayEVM",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTokenList",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTokensMetadata",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "addresses",
              type: "address[]",
              internalType: "address[]",
            },
            {
              name: "names",
              type: "string[]",
              internalType: "string[]",
            },
            {
              name: "symbols",
              type: "string[]",
              internalType: "string[]",
            },
            {
              name: "decimals",
              type: "uint8[]",
              internalType: "uint8[]",
            },
            {
              name: "balances",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isWhitelisted",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "onRevert",
          inputs: [
            {
              name: "revertContext",
              type: "tuple",
              internalType: "struct RevertContext",
              components: [
                {
                  name: "sender",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "asset",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "revertMessage",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingOwner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "permit2",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IPermit2",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "protocolFee",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "removeToken",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "swapFee",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint24",
              internalType: "uint24",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "swapRouter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISwapRouter",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "universalDApp",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "wNativeToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address payable",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdrawFees",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawTokenFees",
          inputs: [
            {
              name: "tokens",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "FeesWithdrawn",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferStarted",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Reverted",
          inputs: [
            {
              name: "recipient",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "asset",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Swapped",
          inputs: [
            {
              name: "executor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "swaps",
              type: "tuple[]",
              indexed: false,
              internalType: "struct EvmDustTokens.SwapOutput[]",
              components: [
                {
                  name: "tokenIn",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "tokenOut",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountIn",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "amountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "totalTokensReceived",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SwappedAndDeposited",
          inputs: [
            {
              name: "executor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "swaps",
              type: "tuple[]",
              indexed: false,
              internalType: "struct EvmDustTokens.SwapOutput[]",
              components: [
                {
                  name: "tokenIn",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "tokenOut",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountIn",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "amountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "totalTokensReceived",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenAdded",
          inputs: [
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenFeesWithdrawn",
          inputs: [
            {
              name: "token",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenRemoved",
          inputs: [
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Withdrawn",
          inputs: [
            {
              name: "recipient",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "outputToken",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "totalTokensReceived",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "FeeWithdrawalFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientAllowance",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "InsufficientBalance",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "InvalidAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidMsgValue",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidToken",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "NoSwaps",
          inputs: [],
        },
        {
          type: "error",
          name: "NotGateway",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SwapFailed",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "revertData",
              type: "bytes",
              internalType: "bytes",
            },
          ],
        },
        {
          type: "error",
          name: "TokenIsNotWhitelisted",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "TokenIsWhitelisted",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "TransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "WrongIndex",
          inputs: [],
        },
      ],
      inheritedFunctions: {
        acceptOwnership:
          "lib/openzeppelin-contracts/contracts/access/Ownable2Step.sol",
        owner: "lib/openzeppelin-contracts/contracts/access/Ownable2Step.sol",
        pendingOwner:
          "lib/openzeppelin-contracts/contracts/access/Ownable2Step.sol",
        renounceOwnership:
          "lib/openzeppelin-contracts/contracts/access/Ownable2Step.sol",
        transferOwnership:
          "lib/openzeppelin-contracts/contracts/access/Ownable2Step.sol",
      },
    },
    SimpleSwap: {
      address: "0x1e0e5af488f94ab21f7ac395d86f9c153c8583ae",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_swapRouter",
              type: "address",
              internalType: "contract ISwapRouter",
            },
            {
              name: "_WETH9",
              type: "address",
              internalType: "address payable",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "ExecuteMultiSwapFromWETH",
          inputs: [
            {
              name: "tokenAddresses",
              type: "address[]",
              internalType: "address[]",
            },
            {
              name: "amountIn",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "WETH9",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address payable",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "swapRouter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISwapRouter",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {
        allowance: "lib/forge-std/src/interfaces/IERC20.sol",
        approve: "lib/forge-std/src/interfaces/IERC20.sol",
        balanceOf: "lib/forge-std/src/interfaces/IERC20.sol",
        decimals: "lib/forge-std/src/interfaces/IERC20.sol",
        name: "lib/forge-std/src/interfaces/IERC20.sol",
        symbol: "lib/forge-std/src/interfaces/IERC20.sol",
        totalSupply: "lib/forge-std/src/interfaces/IERC20.sol",
        transfer: "lib/forge-std/src/interfaces/IERC20.sol",
        transferFrom: "lib/forge-std/src/interfaces/IERC20.sol",
      },
    },
  },
  84532: {
    SimpleSwap: {
      address: "0x87403f6d3dc3ea0563af9c036136923a9d27a9f9",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_swapRouter",
              type: "address",
              internalType: "contract ISwapRouter",
            },
            {
              name: "_WETH9",
              type: "address",
              internalType: "address payable",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "ExecuteMultiSwapFromWETH",
          inputs: [
            {
              name: "tokenAddresses",
              type: "address[]",
              internalType: "address[]",
            },
            {
              name: "amountIn",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "WETH9",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address payable",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "swapRouter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISwapRouter",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {
        allowance: "lib/forge-std/src/interfaces/IERC20.sol",
        approve: "lib/forge-std/src/interfaces/IERC20.sol",
        balanceOf: "lib/forge-std/src/interfaces/IERC20.sol",
        decimals: "lib/forge-std/src/interfaces/IERC20.sol",
        name: "lib/forge-std/src/interfaces/IERC20.sol",
        symbol: "lib/forge-std/src/interfaces/IERC20.sol",
        totalSupply: "lib/forge-std/src/interfaces/IERC20.sol",
        transfer: "lib/forge-std/src/interfaces/IERC20.sol",
        transferFrom: "lib/forge-std/src/interfaces/IERC20.sol",
      },
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
